// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzwtzmmjyrhcpikrixtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6d3R6bW1qeXJoY3Bpa3JpeHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzk0OTMsImV4cCI6MjA2NDIxNTQ5M30.iUEsFaQPx6P1ma8S4kDEDzuJQbSA_qmvR-snRg89K9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);